name: Lotisa Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Linux Build
      run: cargo build --release --verbose
    - name: Archive Linux Build
      uses: actions/upload-artifact@v3
      with:
        name: lotisa
        path: release/lotisa
        