name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Linux Build
      run: cargo build --release --verbose
    - name: Windows Build
      run: cargo build --release --verbose --target x86_64-pc-windows-gnu
    - name: Archive Linux Build
      uses: actions/upload-artifact@v3
      with:
        name: lotisa
        path: release/lotisa
    - name: Archive Github Build
      uses: actions/upload-artifact@v3
      with:
        name: lotisa
        path: x86_64-pc-windows-gnu/lotisa.exe
        